# Generated by Django 3.2.7 on 2021-12-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryes', '0002_subcategory'),
        ('posts', '0003_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategoryes',
            field=models.ManyToManyField(to='categoryes.Subcategory'),
        ),
    ]
