# Generated by Django 4.2.1 on 2023-07-07 08:31

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('task_description', models.CharField(max_length=60)),
                ('review', models.TextField(blank=True)),
                ('quality_of_service', models.PositiveIntegerField(default=3, validators=[account.models.validate_rating])),
                ('adherence_to_deadlines', models.PositiveIntegerField(default=3, validators=[account.models.validate_rating])),
                ('communication_responsiveness', models.PositiveIntegerField(default=3, validators=[account.models.validate_rating])),
                ('price_value_ratio', models.PositiveIntegerField(default=3, validators=[account.models.validate_rating])),
                ('overall_satisfaction', models.PositiveIntegerField(default=3, validators=[account.models.validate_rating])),
                ('rating', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.review')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='account.review'),
        ),
    ]
