# Generated by Django 3.2.7 on 2021-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_auto_20211209_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
