# Generated by Django 3.2.7 on 2021-12-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_alter_dialog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
